config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  devise_for :users
  resources :users

  # get 'static_pages/home'

  # get 'static_pages/help'

  get 'help', to: "static_pages#help"

  get 'tasks/:id/iCal', to: "tasks#iCal", as: "iCal"


  get 'tasks/:id/sms', to: "tasks#sms", as: "sms"

  root "static_pages#home"

end

app/models/task.rb
class Task < ActiveRecord::Base

  belongs_to :user
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tasks

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception



  before_action :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters      
      devise_parameter_sanitizer.permit(:sign_up, keys: [:mobile, :email, :password, :password_confirmation])

      devise_parameter_sanitizer.permit(:account_update, keys: [:mobile, :email, :password, :password_confirmation])
    end  


    protected
    def after_sign_in_path_for(resource)
      tasks_path
    end
end


def icon_category(type)

  if type == "work"
    "fa fa-beer"
  elsif type == "life"
    "fa fa-bicycle"
  elsif type == "fun"
    "fa fa-diamond"
  elsif type == "vip"
    "fa fa-gamepad"
  else
    "fa fa-exclamation"
  end   

end


def time_till_task(days)

    if days <= 1
      "today"
    elsif days <= 2
      "one-day"
    elsif days <= 3
      "two-day"
    else
      "chill"
    end   

  end

def overdue_tasks()


  #  @counter = 0

  #  @tasks.each do |task| 

  #    if task.user.nil?

  #    else

  #     if current_user.email == task.user.email

  #       (task.date - Date.today)

  #     end
  
  #    end

  # end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home

  end

  def help
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!


  # GET /tasks
  # GET /tasks.json

def iCal
  
    @task = Task.find(params[:id])
    # Create a calendar with an event (standard method)
    cal = Icalendar::Calendar.new
    cal.event do |e|
      e.dtstart     = Icalendar::Values::Date.new(@task.date)
      e.summary     = "#{@task.category} #{@task.title}"
      e.ip_class    = "PRIVATE"
    end

   cal.publish
   render text: cal.to_ical, content_type: 'text/calendar'
    
end


def sms


    @task = Task.find(params[:id])

    smsMessage = "#{@task.user.email}, you have #{(@task.date - Date.today).to_s.chop.chop.to_i} day(s) till your #{@task.category} task:#{@task.title}. Are you ready?!?!"


    sms = TestSms.hello_user(@task.user.mobile,"Remy-App",smsMessage)

    puts sms
    sms.deliver

    @task = nil
    redirect_to tasks_url

end

  def index



    @tasks = Task.order('user_id ASC').reorder('date ASC')    

  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    @task.user = current_user

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :date, :time, :category, :tminus)
    end
end

app/controllers/users_controller.rb
  class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!


  # GET /users
  # GET /users.json
  def index
    redirect_to tasks_path
  end

  # GET /users/1
  # GET /users/1.json
  def show
    redirect_to tasks_path
  end

  # GET /users/new
  def new
    redirect_to tasks_path
  end

  # GET /users/1/edit
  def edit
    redirect_to tasks_path

  end

  # POST /users
  # POST /users.json
  def create
    redirect_to tasks_path

  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    redirect_to tasks_path

  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    redirect_to tasks_path

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:mobile)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link href='https://fonts.googleapis.com/css?family=Slabo+27px' rel='stylesheet' type='text/css'>
      <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

  <title>RemyApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css"> 
  <%= csrf_meta_tags %>
</head>
      <body>
            <main>
                <div class="background-image"></div>

                <div class="container" >
                <div class="row " >

                <div class="col-xs-1"></div>
                <div class="col-xs-10 content center-me">
                <div id="primary-content">

                      <p class="alert"><%= alert %></p>  
                      <%= yield  %>
                </div>
                </div>

                <div class="col-xs-1"></div>
                </div>
                </div> <!-- /container -->

            </main>
      </body>
</html>

app/views/static_pages/help.html.erb
<div class='login'>
  <% if current_user %>
     <%= current_user.email %>
     <%= link_to "Log out", destroy_user_session_path, method: :delete %>
  <% else %>
     <%= link_to "Sign In", new_user_session_path %>
     <%= link_to "Register", new_user_registration_path %>
  <% end %>
</div>

app/views/static_pages/home.html.erb
<div class="row">
    <div class="col-xs-2 col-md-4 col-lg-4 center-me"></div>
        
      <div class="col-xs-8 col-md-4 col-lg-4">

        <div class="top-spacer">
          
        <h1> Remy </h1>
        <br>
        <p>Keep track of your life</p>
        <p>One task at a time</p>
        </div>

      </div>

    <div class="col-xs-2 col-md-4 col-lg-4 center-me"></div>

</div>

<br>
<br>


<div class="row">


    <form class="form-signin">

        <div class="row">
          <div class="col-xs-2 col-md-4 col-lg-4 center-me"></div>
              
            <div class="col-xs-8 col-md-4 col-lg-4 center-me">
                 <a id="sign-in-link" class="options" href="<%= new_user_session_path %>"><h2>Sign in</h2></a>
            </div>


          <div class="col-xs-2 col-md-4 col-lg-4 center-me"></div>

        </div>

    <br>



    <div class="row">
          <div class="col-xs-2 col-md-4 col-lg-4 center-me"></div>
              
            <div class="col-xs-8 col-md-4 col-lg-4 center-me">
                 <a  id="register-link" class="options" href="<%=  new_user_registration_path  %>"><h2>Register</h2></a>
            </div>

          <div class="col-xs-2 col-md-4 col-lg-4 center-me"></div>
        </div>

    </form>

</div>

<br>

<div class="row box-me"></div>

<!-- 
<div class="row">
<div class="col-xs-2 col-md-4 col-lg-4 center-me"></div>
    
  <div class="col-xs-8 col-md-4 col-lg-4">

    <div class="bottom-spacer">

    </div>

  </div>

<div class="col-xs-2 col-md-4 col-lg-4 center-me"></div>

</div>


 -->

app/views/tasks/_form.html.erb
<% if @task.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

    <ul>
    <% @task.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(@task) do |f| %>

<div class="row">
    <div class="col-xs-2 col-md-4 col-lg-4 center-me rm-pad"></div>
        
      <div class="col-xs-8 col-md-4 col-lg-4 center-me">
        <div class="field">
          <br>
          <%= f.text_field :title, placeholder: ":Title", class: "style-5" %>
        </div>
      </div>

    <div class="col-xs-2 col-md-4 col-lg-4 center-me"></div>

</div>

<div class="row">
    <div class="col-xs-1 col-md-4 col-lg-4 center-me rm-pad"></div>
        
      <div class="col-xs-10 col-md-4 col-lg-4 center-me">
          <div class="field">
          <%= f.label :date %><br>
          <%= f.date_select :date %>
          </div>
      </div>

    <div class="col-xs-1 col-md-4 col-lg-4 center-me"></div>

</div>

<div class="row">
    <div class="col-xs-2 col-md-4 col-lg-4 center-me rm-pad"></div>
        
      <div class="col-xs-8 col-md-4 col-lg-4 center-me">
        <div class="field">
            <%= f.label :time %><br>
            <%= f.time_select :time %>
        </div>
      </div>

    <div class="col-xs-2 col-md-4 col-lg-4 center-me"></div>

</div>

<br>

<div class="row">
    <div class="col-xs-2 col-md-4 col-lg-4 center-me rm-pad"></div>
        
      <div class="col-xs-4 col-md-4 col-lg-4">
          <br>
          <div class="field">
          <div class="center-me">
          <label >Category</label>
          </div>
                      <div>
                        <input id="question1" type="radio" value="work" name="task[category]" class="with-font"  />
                        <label for="question1">Work</label>
                      </div>
                      <div>
                        <input id="question2" name="task[category]" type="radio" class="with-font" value="life"/>
                        <label for="question2">Life</label>
                      </div>
                      <div>
                        <input id="question3" name="task[category]" type="radio" class="with-font" value="fun"/>
                        <label for="question3">Fun</label>
                      </div>
                      <div>
                        <input id="question4" name="task[category]" type="radio" class="with-font" value="vip"/>
                        <label for="question4">VIP</label>
                      </div>
          </div>
      </div> 

      <div class="col-xs-4 col-md-4 col-lg-4">
          <br>
          <div class="field">
          <div class="center-me">
          <label>Sms</label>
          </div>
                      <div>
                        <input id="question5" type="radio" value="1 Mins" name="task[tminus]" class="with-font"  />
                        <label for="question5">1 Mins</label>
                      </div>
                      <div>
                        <input id="question6" name="task[tminus]" type="radio" class="with-font" value="15"/>
                        <label for="question6">15 Mins</label>
                      </div>
                      <div>
                        <input id="question7" name="task[tminus]" type="radio" class="with-font" value="30"/>
                        <label for="question7">30 Mins</label>
                      </div>
                      <div>
                        <input id="question8" name="task[tminus]" type="radio" class="with-font" value="60"/>
                        <label for="question8">1 Hour</label>
                      </div>
          </div>
      </div>

    <div class="col-xs-2 col-md-4 col-lg-4 center-me"></div>

</div>





<div class="row">
    <div class="col-xs-2 col-md-4 col-lg-4 center-me"></div>
        
      <div class="col-xs-8 col-md-4 col-lg-4 center-me">
      
      </div>

    <div class="col-xs-2 col-md-4 col-lg-4 center-me"></div>

</div>

<br>

<div class="row">
      <div class="col-xs-2 col-md-4 col-lg-4 center-me"></div>
          
        <div class="col-xs-8 col-md-4 col-lg-4">

          <div class="row center-me">
            <div class="col-xs-6">
              <a href="<%= tasks_path %>"><i class="fa fa-undo fa-2x" aria-hidden="true"></i></a>
            </div>
              
            <div class="col-xs-6 center-me">
              <div class="actions center-me">
                    <button id="btnTimer" type="submit" class="login center-me">
                    <i class="fa fa-check fa-2x" aria-hidden="true"></i>
                    </button>            
              </div>
            </div>

       
          <br />

          </div>
        </div>
    <div class="col-xs-2 col-md-4 col-lg-4 center-me"></div>
</div>


  <% end %>

app/views/tasks/edit.html.erb
<div class="row">
    <div class="col-xs-2 col-md-4 col-lg-4 center-me"></div>
        
      <div class="col-xs-8 col-md-4 col-lg-4">

        <div class="top-spacer-new">
          
        <h1> Edit Task </h1>

        </div>

      </div>

    <div class="col-xs-2 col-md-4 col-lg-4 center-me"></div>

</div>

<%= render 'form' %>

app/views/tasks/index.html.erb
 
 <div class="row box-me">

    <div class="col-xs-1 go-left">
        <% if current_user %>
        <a href= <%=edit_user_registration_path(current_user) %> ><i class="fa fa-user" aria-hidden="true"></i></a>

        <% else %>
           <%= link_to "Sign In", new_user_session_path %>
           <%= link_to "Register", new_user_registration_path %>
        <% end %>
    </div>

    <div class="col-xs-3 go-left">  
      <div class='login'>
      <%= link_to "Log out", destroy_user_session_path, method: :delete %>
        
      </div>
    </div>

    <div class="col-xs-6 center-me box-me"></div>  

    <div class="col-xs-1 go-right">
      <a href= <%= new_task_path%> ><i class="fa fa-pencil" aria-hidden="true"></i></a>


    </div>
</div>

<div id="fix-row" class="row center-me">

    <div class="col-xs-6 task-left"> 

    <div><h2>To-Do</h2>
    <div class="big-me">
      <%= current_user.tasks.length %>
    </div>
    </div>


    </div>

    <div class="col-xs-6 task-done"> 

    <div><h2>Overdue</h2>
    <div class="big-me">

    <% @counter = 0 %>

    <% @tasks.each do |task| %>

    <% if task.user.nil? %>

    <%   else %>

    <%   if current_user.email == task.user.email && (task.date - Date.today).to_s.chop.chop.to_i < 0 %>

          <% @counter = @counter + 1 %>

    <%    end %>
    
    <%   end %>

    <% end %>

    <%= @counter %>


    </div>
    </div>



    </div>


</div>

<br>




 <% @tasks.each do |task| %>


<% if task.user.nil? %>

<% else %>

     <% if current_user.email == task.user.email %>

    <!-- top of the task -->
       
       <div id="fix-row" class="row <%= time_till_task( (task.date - Date.today).to_s.chop.chop.to_i )%>">

         <!-- category icon  -->
          <div class="col-xs-2 center-me"><i class="<%= icon_category(task.category) %>" aria-hidden="true"></i></div>

          <!-- display days till I'm due -->
          <div class="col-xs-2 center-me"><%= (task.date - Date.today).to_s.chop.chop.to_i %></div>

              
            <div class="col-xs-6 center-me"><a href="<%= edit_task_path(task) %>"><%= task.title %></a></div>
            <div class="col-xs-2 center-me">

            <%= link_to  '<i class="fa fa-calendar-plus-o" aria-hidden="true"></i>'.html_safe, iCal_path(task) , :format => :ics %>

            <%= link_to '<i class="fa fa-mobile" aria-hidden="true"></i>'.html_safe,sms_path(task), data: { confirm: 'Send Text?' } %>


            <%= link_to '<i class="fa fa-trash-o" aria-hidden="true"></i>'.html_safe, task, method: :delete, data: { confirm: 'Are you sure?' } %>


            </div>

        </div>
      <% end %>

      <% end %>
      <% end %>
  
  

app/views/tasks/new.html.erb
<div class="row">
    <div class="col-xs-2 col-md-4 col-lg-4 center-me"></div>
        
      <div class="col-xs-8 col-md-4 col-lg-4">

        <div class="top-spacer-new">
          
        <h1> New Task </h1>

        </div>

      </div>

    <div class="col-xs-2 col-md-4 col-lg-4 center-me"></div>

</div>

<%= render 'form' %>

app/views/tasks/show.html.erb
<div class="row">

    <div class="col-xs-2 col-md-4 col-lg-4 center-me"></div>
        
      <div class="col-xs-8 col-md-4 col-lg-4">

        <div class="top-spacer-sign">
          <h1 class="form-signin-heading"><%= notice %></h1>
        </div>

      </div>

    <div class="col-xs-2 col-md-4 col-lg-4 center-me"></div>

</div>

<br>


<div class="row">
    <div class="col-xs-2 col-md-4 col-lg-4 center-me rm-pad"></div>
        
      <div class="col-xs-8 col-md-4 col-lg-4 center-me">
        <div class="field">
          <br>
          <p>
            <strong>Reminder:</strong>
            <%= @task.title %>
          </p>

        </div>
      </div>

    <div class="col-xs-2 col-md-4 col-lg-4 center-me"></div>

</div>

<br>



<div class="row">
    
        
      <div class="col-xs-6 center-me">
        <div class="field">
         <p>
           <strong>Date:</strong>
           <%= @task.date %>
         </p>


        </div>
      </div>

      <div class="col-xs-6 center-me">
        <div class="field">
         <p>
           <strong>Time:</strong>
           <%= @task.time.strftime("%H:%M") %>
         </p>
        </div>
      </div>

    

</div>



<div class="row">
    
        
      <div class="col-xs-6 center-me">
        <div class="field">
         <p>
           <strong>Category:</strong>
           <% if @task.category.nil? %>
           <p>No Category</p>
           <% else %>
           <%= @task.category %>

           <% end %>
           
         </p>


        </div>
      </div>

      <div class="col-xs-6 center-me">
        <div class="field">
         <p>
           <strong>Remind @:</strong>
           <% if @task.tminus.nil? %>
           <p>No reminder</p>
           <% else %>
           <%= (@task.time - @task.tminus).strftime("%H:%M") %>

           <% end %>
         </p>

        </div>
      </div>

    

</div>

<br>



<div class="row center-me">
  <div class="col-xs-12">
    <a href="<%= tasks_path %>"><i class="fa fa-check fa-5x" aria-hidden="true"></i></a>
  </div>
</div>

<br>
<br>